---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
      memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.14

platforms:
  - name: macosx-10.10
    driver:
      box: dhoer/macosx-10.10
suites:
  - name: macosx_gui_login_test
    run_list:
    - recipe[macosx_gui_login_test::default]
    attributes:
